HIP_PATH?= /opt/rocm
HIPCC=$(HIP_PATH)/bin/hipcc

# MEMCPY_PERSISTENT
CXXFLAGS+=-DENABLE_MEMCPY_PERSISTENT=$(ENABLE_MEMCPY_PERSISTENT)
CXXFLAGS+=-DMEMCPY_PERSISTENT_GS_VAL=$(MEMCPY_PERSISTENT_GS_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_BS_VAL=$(MEMCPY_PERSISTENT_BS_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_PIXELS_MB_VAL=$(MEMCPY_PERSISTENT_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_UNROLL_VAL=$(MEMCPY_PERSISTENT_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_VERIFY=$(MEMCPY_PERSISTENT_VERIFY)

# READ
CXXFLAGS+=-DENABLE_MEMREAD_STREAM=$(ENABLE_MEMREAD_STREAM)
CXXFLAGS+=-DREAD_GS_VAL=$(READ_GS_VAL)
CXXFLAGS+=-DREAD_BS_VAL=$(READ_BS_VAL)
CXXFLAGS+=-DREAD_PIXELS_MB_VAL=$(READ_PIXELS_MB_VAL)
CXXFLAGS+=-DREAD_UNROLL_VAL=$(READ_UNROLL_VAL)
CXXFLAGS+=-DREAD_STREAM_NONTEMP=$(READ_STREAM_NONTEMP)
CXXFLAGS+=-DREAD_VERIFY=$(READ_VERIFY)

# MEMCPY
CXXFLAGS+=-DENABLE_MEMCPY_STREAM=$(ENABLE_MEMCPY_STREAM)
CXXFLAGS+=-DMEMCPY_GS_VAL=$(MEMCPY_GS_VAL)
CXXFLAGS+=-DMEMCPY_BS_VAL=$(MEMCPY_BS_VAL)
CXXFLAGS+=-DMEMCPY_PIXELS_MB_VAL=$(MEMCPY_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_UNROLL_VAL=$(MEMCPY_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_NONTEMP=$(MEMCPY_STREAM_NONTEMP)
CXXFLAGS+=-DMEMCPY_STREAM_VERIFY=$(MEMCPY_STREAM_VERIFY)

# MEMCPY_ASYNC
CXXFLAGS+=-DENABLE_MEMCPY_STREAM_ASYNC=$(ENABLE_MEMCPY_STREAM_ASYNC)
CXXFLAGS+=-DMEMCPY_ASYNC_GS_VAL=$(MEMCPY_ASYNC_GS_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_BS_VAL=$(MEMCPY_ASYNC_BS_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_PIXELS_MB_VAL=$(MEMCPY_ASYNC_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_UNROLL_VAL=$(MEMCPY_ASYNC_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_ASYNC_VERIFY=$(MEMCPY_STREAM_ASYNC_VERIFY)

# MEMCPY_SWIZZLED
CXXFLAGS+=-DENABLE_MEMCPY_STREAM_SWIZZLED=$(ENABLE_MEMCPY_STREAM_SWIZZLED)
CXXFLAGS+=-DMEMCPY_SWIZZLED_GS_VAL=$(MEMCPY_SWIZZLED_GS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_BS_VAL=$(MEMCPY_SWIZZLED_BS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_PIXELS_MB_VAL=$(MEMCPY_SWIZZLED_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_CHUNKS_VAL=$(MEMCPY_SWIZZLED_CHUNKS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_INNER_VAL=$(MEMCPY_SWIZZLED_INNER_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_SWIZZLED_NONTEMP=$(MEMCPY_STREAM_SWIZZLED_NONTEMP)
CXXFLAGS+=-DMEMCPY_STREAM_SWIZZLED_VERIFY=$(MEMCPY_STREAM_SWIZZLED_VERIFY)

ifdef DEBUG
CXXFLAGS+=-DDEBUG=$(DEBUG)
endif


srcs := memcpy_async.cc
deps := memcpy_async.o

memcpy_async: memcpy_async.cc
	$(HIPCC) $(CXXFLAGS) -std=c++17 -O3 -Wall --offload-arch=gfx942 -DHIP $^ $(EXTRA_FLAGS) -o $@

.PHONY: clean
clean:
	rm -f memcpy_async
