HIP_PATH?= /opt/rocm
HIPCC=$(HIP_PATH)/bin/hipcc

ifndef MEMCPY_PERSISTENT_GS_VAL
MEMCPY_PERSISTENT_GS_VAL=0
endif

ifndef MEMCPY_PERSISTENT_BS_VAL
MEMCPY_PERSISTENT_BS_VAL=0
endif

ifndef MEMCPY_PERSISTENT_PIXELS_MB_VAL
MEMCPY_PERSISTENT_PIXELS_MB_VAL=0
endif

ifndef MEMCPY_PERSISTENT_UNROLL_VAL
MEMCPY_PERSISTENT_UNROLL_VAL=0
endif

ifndef READ_GS_VAL
READ_GS_VAL=0
endif

ifndef READ_BS_VAL
READ_BS_VAL=0
endif

ifndef READ_PIXELS_MB_VAL
READ_PIXELS_MB_VAL=0
endif

ifndef READ_UNROLL_VAL
READ_UNROLL_VAL=0
endif

ifndef READ_STREAM_NONTEMP
READ_STREAM_NONTEMP=0
endif

ifndef ENABLE_MEMREAD_STREAM
ENABLE_MEMREAD_STREAM=0
endif

ifndef MEMCPY_GS_VAL
MEMCPY_GS_VAL=0
endif

ifndef MEMCPY_BS_VAL
MEMCPY_BS_VAL=0
endif

ifndef MEMCPY_PIXELS_MB_VAL
MEMCPY_PIXELS_MB_VAL=0
endif

ifndef MEMCPY_UNROLL_VAL
MEMCPY_UNROLL_VAL=0
endif

ifndef MEMCPY_ASYNC_GS_VAL
MEMCPY_ASYNC_GS_VAL=0
endif

ifndef MEMCPY_ASYNC_BS_VAL
MEMCPY_ASYNC_BS_VAL=0
endif

ifndef MEMCPY_ASYNC_PIXELS_MB_VAL
MEMCPY_ASYNC_PIXELS_MB_VAL=0
endif

ifndef MEMCPY_ASYNC_UNROLL_VAL
MEMCPY_ASYNC_UNROLL_VAL=0
endif

ifndef MEMCPY_SWIZZLED_GS_VAL
MEMCPY_SWIZZLED_GS_VAL=0
endif

ifndef MEMCPY_SWIZZLED_BS_VAL
MEMCPY_SWIZZLED_BS_VAL=0
endif

ifndef MEMCPY_SWIZZLED_PIXELS_MB_VAL
MEMCPY_SWIZZLED_PIXELS_MB_VAL=0
endif

ifndef MEMCPY_SWIZZLED_CHUNKS_VAL
MEMCPY_SWIZZLED_CHUNKS_VAL=0
endif

ifndef MEMCPY_SWIZZLED_INNER_VAL
MEMCPY_SWIZZLED_INNER_VAL=0
endif

ifndef READ_VERIFY
READ_VERIFY=0
endif

ifndef MEMCPY_STREAM_NONTEMP
MEMCPY_STREAM_NONTEMP=0
endif

ifndef MEMCPY_STREAM_SWIZZLED_NONTEMP
MEMCPY_STREAM_SWIZZLED_NONTEMP=0
endif

ifndef ENABLE_MEMCPY_PERSISTENT
ENABLE_MEMCPY_PERSISTENT=0
endif

ifndef ENABLE_MEMCPY_STREAM
ENABLE_MEMCPY_STREAM=0
endif

ifndef ENABLE_MEMCPY_STREAM_ASYNC
ENABLE_MEMCPY_STREAM_ASYNC=0
endif

ifndef ENABLE_MEMCPY_STREAM_SWIZZLED
ENABLE_MEMCPY_STREAM_SWIZZLED=0
endif

ifndef MEMCPY_PERSISTENT_VERIFY
MEMCPY_PERSISTENT_VERIFY=0
endif

ifndef MEMCPY_STREAM_SWIZZLED_VERIFY
MEMCPY_STREAM_SWIZZLED_VERIFY=0
endif

ifndef MEMCPY_STREAM_ASYNC_VERIFY
MEMCPY_STREAM_ASYNC_VERIFY=0
endif

ifndef MEMCPY_STREAM_VERIFY
MEMCPY_STREAM_VERIFY=0
endif

# MEMCPY_PERSISTENT
CXXFLAGS+=-DENABLE_MEMCPY_PERSISTENT=$(ENABLE_MEMCPY_PERSISTENT)
CXXFLAGS+=-DMEMCPY_PERSISTENT_GS_VAL=$(MEMCPY_PERSISTENT_GS_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_BS_VAL=$(MEMCPY_PERSISTENT_BS_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_PIXELS_MB_VAL=$(MEMCPY_PERSISTENT_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_UNROLL_VAL=$(MEMCPY_PERSISTENT_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_PERSISTENT_VERIFY=$(MEMCPY_PERSISTENT_VERIFY)

# READ
CXXFLAGS+=-DENABLE_MEMREAD_STREAM=$(ENABLE_MEMREAD_STREAM)
CXXFLAGS+=-DREAD_GS_VAL=$(READ_GS_VAL)
CXXFLAGS+=-DREAD_BS_VAL=$(READ_BS_VAL)
CXXFLAGS+=-DREAD_PIXELS_MB_VAL=$(READ_PIXELS_MB_VAL)
CXXFLAGS+=-DREAD_UNROLL_VAL=$(READ_UNROLL_VAL)
CXXFLAGS+=-DREAD_STREAM_NONTEMP=$(READ_STREAM_NONTEMP)
CXXFLAGS+=-DREAD_VERIFY=$(READ_VERIFY)

# MEMCPY
CXXFLAGS+=-DENABLE_MEMCPY_STREAM=$(ENABLE_MEMCPY_STREAM)
CXXFLAGS+=-DMEMCPY_GS_VAL=$(MEMCPY_GS_VAL)
CXXFLAGS+=-DMEMCPY_BS_VAL=$(MEMCPY_BS_VAL)
CXXFLAGS+=-DMEMCPY_PIXELS_MB_VAL=$(MEMCPY_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_UNROLL_VAL=$(MEMCPY_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_NONTEMP=$(MEMCPY_STREAM_NONTEMP)
CXXFLAGS+=-DMEMCPY_STREAM_VERIFY=$(MEMCPY_STREAM_VERIFY)

# MEMCPY_ASYNC
CXXFLAGS+=-DENABLE_MEMCPY_STREAM_ASYNC=$(ENABLE_MEMCPY_STREAM_ASYNC)
CXXFLAGS+=-DMEMCPY_ASYNC_GS_VAL=$(MEMCPY_ASYNC_GS_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_BS_VAL=$(MEMCPY_ASYNC_BS_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_PIXELS_MB_VAL=$(MEMCPY_ASYNC_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_ASYNC_UNROLL_VAL=$(MEMCPY_ASYNC_UNROLL_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_ASYNC_VERIFY=$(MEMCPY_STREAM_ASYNC_VERIFY)

# MEMCPY_SWIZZLED
CXXFLAGS+=-DENABLE_MEMCPY_STREAM_SWIZZLED=$(ENABLE_MEMCPY_STREAM_SWIZZLED)
CXXFLAGS+=-DMEMCPY_SWIZZLED_GS_VAL=$(MEMCPY_SWIZZLED_GS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_BS_VAL=$(MEMCPY_SWIZZLED_BS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_PIXELS_MB_VAL=$(MEMCPY_SWIZZLED_PIXELS_MB_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_CHUNKS_VAL=$(MEMCPY_SWIZZLED_CHUNKS_VAL)
CXXFLAGS+=-DMEMCPY_SWIZZLED_INNER_VAL=$(MEMCPY_SWIZZLED_INNER_VAL)
CXXFLAGS+=-DMEMCPY_STREAM_SWIZZLED_NONTEMP=$(MEMCPY_STREAM_SWIZZLED_NONTEMP)
CXXFLAGS+=-DMEMCPY_STREAM_SWIZZLED_VERIFY=$(MEMCPY_STREAM_SWIZZLED_VERIFY)


ifdef DEBUG
CXXFLAGS+=-DDEBUG=$(DEBUG)
endif

srcs := membench.cc
deps := membench.o

membench: membench.cc
ifdef ARCH
	$(HIPCC) $(CXXFLAGS) -std=c++17 -O3 -Wall --offload-arch=$(ARCH) -DHIP $^ $(EXTRA_FLAGS) -o $@
else
	$(HIPCC) $(CXXFLAGS) -std=c++17 -O3 -Wall -DHIP $^ $(EXTRA_FLAGS) -o $@
endif




.PHONY: clean
clean:
	rm -f membench
